pipeline {
    agent any
    parameters {
        choice(name: 'TEST_SUITE', choices: ['ui', 'api', 'fast_ui', 'slow_ui', 'smoke_ui'],
        description: 'Choose the test suite to run')
    }
    stages {
        stage('Setup Environment') {
            steps {
                script {
                    sh '''
                        python3 -m venv venv
                        . venv/bin/activate
                        pip install -r requirements.txt
                    '''
                }
            }
        }
        stage('Run Tests') {
            steps {
                script {
                    sh """
                        . venv/bin/activate
                        pytest --alluredir=allure-results -m ${params.TEST_MARKER}
                    """
                }
            }
        }
    }
    post {
        always {
            allure includeProperties: false, jdk: '', results: [[path: 'allure-results']]
        }
    }
}
