name: Auto Assign

on:
  pull_request:
    types: [opened, ready_for_review]
    branches: [main]

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Auto Assign Reviewers
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: '.github/auto_assign_config.yml'
          repo-token: ${{ secrets.PAT }}
