name: Auto Assign

on:
  pull_request:
    types: [ opened, ready_for_review ]
    branches: [ main ]

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - name: Verify Repository Access
        run: |
          echo "Checking repository access..."
          git ls-remote https://github.com/MarieAmbrazhei/final_project_group_a.git

      - name: Auto Assign Reviewers
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: '.github/auto_assign_config.yml'
