name: Pylint

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, reopened, edited, synchronize ]
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Analysing the code with pylint
        run: pylint --disable=C0112,C0114,C0115,C0116,C0103,R1705,R0903,R0902,W0123,W0621,R0801,R0915,W0105,W0106,W0612,R0913,C0209,E1101,W1514 **/*.py

